### numpy documentation
https://numpy.org/doc/stable/

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.30925719 0.00132129 0.23146481 0.41181971 0.83780157]
 [0.13693743 0.69299718 0.85464418 0.09837301 0.4400539 ]
 [0.72014212 0.22518427 0.03257085 0.12355484 0.20710076]]


#### 연산함수
* add, substract, multiply, divide 
* 차원도 같고, 차원의 값(n행n열)도 같아야함

In [3]:
np.add(x, y)

array([[ 0.30925719,  1.00132129,  2.23146481,  3.41181971,  4.83780157],
       [ 5.13693743,  6.69299718,  7.85464418,  8.09837301,  9.4400539 ],
       [10.72014212, 11.22518427, 12.03257085, 13.12355484, 14.20710076]])

In [5]:
np.subtract(x,y)

array([[-0.30925719,  0.99867871,  1.76853519,  2.58818029,  3.16219843],
       [ 4.86306257,  5.30700282,  6.14535582,  7.90162699,  8.5599461 ],
       [ 9.27985788, 10.77481573, 11.96742915, 12.87644516, 13.79289924]])

In [6]:
np.multiply(x,y)

array([[0.00000000e+00, 1.32128544e-03, 4.62929629e-01, 1.23545913e+00,
        3.35120628e+00],
       [6.84687139e-01, 4.15798306e+00, 5.98250927e+00, 7.86984068e-01,
        3.96048506e+00],
       [7.20142116e+00, 2.47702699e+00, 3.90850166e-01, 1.60621288e+00,
        2.89941066e+00]])

In [7]:
x * y #바로 연산자를 사용하기도함

array([[0.00000000e+00, 1.32128544e-03, 4.62929629e-01, 1.23545913e+00,
        3.35120628e+00],
       [6.84687139e-01, 4.15798306e+00, 5.98250927e+00, 7.86984068e-01,
        3.96048506e+00],
       [7.20142116e+00, 2.47702699e+00, 3.90850166e-01, 1.60621288e+00,
        2.89941066e+00]])

In [8]:
np.max(y)

0.8546441817387584

In [9]:
np.argmax(y)

7

In [10]:
np.var(y), np.median(y), np.std(y)

(0.0795252908336392, 0.231464814584032, 0.2820022887028387)

In [12]:
np.sum(y)

5.323223095488665

In [11]:
np.cumsum(y)

array([0.30925719, 0.31057848, 0.54204329, 0.953863  , 1.79166457,
       1.928602  , 2.62159918, 3.47624336, 3.57461637, 4.01467026,
       4.73481238, 4.95999665, 4.9925675 , 5.11612233, 5.3232231 ])

In [13]:
y

array([[0.30925719, 0.00132129, 0.23146481, 0.41181971, 0.83780157],
       [0.13693743, 0.69299718, 0.85464418, 0.09837301, 0.4400539 ],
       [0.72014212, 0.22518427, 0.03257085, 0.12355484, 0.20710076]])

In [15]:
np.sum(y, axis=None)

5.323223095488665

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [16]:
z = np.random.randn(10)
print(z)

[ 2.70613289e-01  8.25101513e-01  2.17102583e-03 -1.89695969e+00
 -4.77852646e-01 -2.85067725e-01 -1.13235902e+00  3.55181837e-01
 -4.65091028e-01  2.23041905e+00]


In [17]:
z > 0

array([ True,  True,  True, False, False, False, False,  True, False,
        True])

In [18]:
np.any(z > 0)

True

In [19]:
np.all(z != 0)

True

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [21]:
z = np.random.randn(10)
print(z)

[ 0.22460301  0.71313091 -0.04224519 -0.3554754  -0.79008556 -1.86122893
  0.40364729 -0.12063162 -1.0895078  -1.42952766]


In [22]:
np.where(z > 0, z, 0)

array([0.22460301, 0.71313091, 0.        , 0.        , 0.        ,
       0.        , 0.40364729, 0.        , 0.        , 0.        ])