In [1]:
import numpy as np
import matplotlib.pyplot as plt

### ndarray 인덱싱&슬라이싱

In [3]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
x[0]
x[-1] #마지막 숫자 가져오기

0

In [5]:
x[3] = 100
print(x)

[  0   1   2 100   4   5   6   7   8   9]


* 2차원 행렬 인덱싱

In [6]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
x[0] #차원이 하나 줄기 때문에 1차원 벡터만 가져오게 됨
x[1] #차원이 하나 줄어든 것

array([5, 6, 7, 8, 9])

In [9]:
x[0, 2] #0번째 행 2번째 열

2

* 3차원 텐서 인덱싱

In [10]:
x = np.arange(36).reshape(3, 4, 3) #4행 3열짜리 행렬이 3개가 쌓여있다
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [11]:
x[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
x[1, 2]

array([18, 19, 20])

In [13]:
x[1, 2, 1]

19

* 1차원 벡터 슬라이싱

In [14]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

* 2차원 행렬 슬라이싱

In [16]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
x[:, 1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [19]:
x[:, :2]

array([[0, 1],
       [5, 6]])

* 3차원 텐서 슬라이싱

In [20]:
x = np.arange(36).reshape(3, 4, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [22]:
x = np.arange(54).reshape(2, 9, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]]


In [23]:
x[:1, :2, :]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [25]:
x[0, :2, :]

array([[0, 1, 2],
       [3, 4, 5]])

### ndarray 데이터 형태를 바꿔보기
ndarray shape 변경하기

#### ravel, np.ravel
* 다차원배열을 1차원으로 변경
* 'order' 파라미터 <br>
</t> * 'C' - row 우선변경 <br>
</t> * 'F' - column 우선변경

In [26]:
x = np.arange(15).reshape(3, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [27]:
np.ravel(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
temp = x.ravel()
print(temp)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [30]:
temp[0] = 100
print(temp)
print(x) #복사본을 만드는 것이 아니라 성능을 위해서 데이터구조를 유지하고 있음

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


flatten
* 다차원 배열을 1차원으로 변경
* ravel과의 차이점: copy를 생성하여 변경함(즉 원본데이터가 아닌 복사본을 봔한)
* order 파라미터 - 

In [33]:
y = np.arange(15).reshape(3, 5)
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
t2 = y.flatten()
print(t2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [35]:
t2[0] = 100
print(t2)
print(y) #t2를 바꾼다고 해도 y가 변경되지 않음

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [37]:
t2 = y.flatten(order='C')
print(t2)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [38]:
x = np.arange(30).reshape(2, 3, 5)
print(x)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [39]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### reshape 함수
* array의 shape를 다른 차원으로 변경
* 주의할점은 reshape한 후의 결과의 전체 원소 개수와 이전 개수가 같아야 가능
* 사용 예) 이미지 데이터 백터화 - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용됨

In [41]:
x= np.arange(36)
print(x)
print(x.shape)
print(x.ndim) #number of dimesion 차원

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
(36,)
1


In [42]:
x.reshape(6, 6) #만약 곱이 맞지 않다면, 변환이 불가능함

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [43]:
y = x.reshape(6, 6)
print(y.shape)
print(y.ndim)

(6, 6)
2


In [44]:
k = x.reshape(3, 3, 4)
print(k)
print(k.shape)
print(k.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
(3, 3, 4)
3
